server:
  port: 8084

spring:
  application:
    name: fraud-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fraud-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

kafka:
  topics:
    transaction-initiated: transaction.initiated

fraud:
  rules:
    max-amount: 50000
    max-transactions-per-minute: 5